### PR TITLE
Adding InfluxDB buffering & batching

### PR DESCRIPTION
**Pull request by BarthV**
- Adding pretty naive & fast buffering + influx batching
- Using multi_json instead of json
- Add buffer age & size options
- Using EM::periodictimer to force buffer flush
- Using Sensu logger instead of raw `puts`
- Update (and fix) readme
- SSL still broken

In InfluxDB docs : 

```
Writing multiple points

Post multiple points to multiple series at the same time by separating each
point with a new line.
Batching points in this manner results in much higher performance.
```

```
Write a Batch of Points

You can also pass a file using the @ flag. The file can contain a batch
of points, one per line.
Points must be separated by newline characters.
Batches should be 5000 points or fewer for best performance.
```

_Consistency & retention policy options are still to add :-)_

### CODE REVIEW

**Comment by BarthV** [comment]
Bump :angel:

**Comment by BarthV** [comment]
bump :)

**Comment by eheydrick** [comment]
Would be nice to see this merged.

**Review by alfredopalhares — APPROVED** [review]

**Comment by alfredopalhares** [comment]
Thank you! Sorry for the delay.

**Pull request merged**
