### PR TITLE
Support Influx 0.9 

### PR DESCRIPTION
**Pull request by BarthV**
Hi :smile: !

This is time to bring huge change to this useful extension !
I did my best to keep things as they were (but I'm not really a big ruby-guru, so please take enough time to review and test this PR by your side).

Changes : 
* using Influx 0.9 Line Protocol
* filtering keyname (strip_metric is still used)
* using sensu client name as default host tag
* adding tags support @ global level & @ check level with some kind of precedence level
* some heavy refactoring in event parsing def & default value handling method
* update readme
* switch to a more "rubocop-compliant" syntax (it's still not perfect)

Still todo : 
* review and refactor
* support new Influx `retention_policy` & `consistency` options @ global level and check level.
* more rubocop
* spec files rewrite ?

At this state it's fully working here (I used strip_metric = 'host' to cleanup hostname in keyname): 
* data from a simple sensu standalone metric check : 
```
> select * from "load_avg.one" WHERE time > now() - 1m;
name: load_avg.one
------------------
time			        duration	host				            value
2015-10-14T14:52:42Z	0.395		myhost-test-sa-01.mycompany.fr	0.74
2015-10-14T14:52:52Z	0.397		myhost-test-sa-01.mycompany.fr	0.62
2015-10-14T14:53:02Z	0.402		myhost-test-sa-01.mycompany.fr	0.76
2015-10-14T14:53:12Z	0.399		myhost-test-sa-01.mycompany.fr	0.93
2015-10-14T14:53:22Z	0.402		myhost-test-sa-01.mycompany.fr	0.79
2015-10-14T14:53:32Z	0.404		myhost-test-sa-01.mycompany.fr	1.06
```

* same load data from a collectd plugin with sensu_write output : 
```
> select * from "load.load.midterm" WHERE time > now() - 1m;
name: load.load.midterm
-----------------------
time			        host				            value
2015-10-14T14:53:23Z	myhost-test-sa-01.mycompany.fr	0.8
2015-10-14T14:53:33Z	myhost-test-sa-01.mycompany.fr	0.85
2015-10-14T14:53:43Z	myhost-test-sa-01.mycompany.fr	0.82
2015-10-14T14:53:53Z	myhost-test-sa-01.mycompany.fr	0.83

```

Maybe, you can store the current master in a "legacy" 0.8 branch and start to work on this base ?
It could be great to work together on this ;) !

Thanks

### CODE REVIEW

**Comment by masterkorp** [comment]
:+1: Please wait until the weekend for me to review this.

**Comment by tleung999** [comment]
Hi there.   I'm sorry to comment on this PR but I was wondering if the extension is currently broken if I am using Influxdb 0.9?   I just setup a new Influx node using their hosting service and after spending half a day trying to get it to work, I found this PR.    I looked on their service and the version they installed was 0.9.4.2.   Please advise.  Thanks!

**Comment by BarthV** [comment]
@tleung999
* the current master of this repo  is working for InfluxD 0.8.X only.
* This PR is a work in progress for 0.9.X. I'm currently using it for my own 0.9.4_2
* so it should be working for _most_ of the metric events sent to Sensu __but__ ... :+1: 
* It may not be much tested & stable
* few line protocol features are not supported yet

**Comment by damm** [comment]
@BarthV I tried your version and I am getting this? doesn't seem to be saying anything

```
{"timestamp":"2015-10-22T00:28:28.967613+0000","level":"info","message":"handler extension output","extension":{"type":"extension","name":"influxdb"},"output":"","status":0}
```

0.9.4.2 as well; don't see any errors on influxdb itself

**Comment by BarthV** [comment]
@damm : I'll check that one more time on a test env.

**Comment by damm** [comment]
@BarthV Any hints on how to debug it?  I might add some log statements as it looks right I can't see any errors it just runs and exits.

**Comment by BarthV** [comment]
@damm 
I worked a couple hours on this issue today.
I started a bare new 0.9.4.2 (influxdb.com free trial) and it seems to be working over http (@ my company) but not over https (@ influxdb.com).
Maybe we missed some https options or em-http-request is in failure with it.

Still investigating why it's not working :)

**Comment by BarthV** [comment]
but sometimes you know ... debugging https can be cumbersome

**Comment by BarthV** [comment]
After more tests, I confirm that http is OK & https is broken (at least on influxdb.com hosted services).

**Comment by BarthV** [comment]
we call :
* https://github.com/igrigorik/em-http-request/blob/3a9b96c2f31f29c112a11b934fee7d40cafd4dcc/lib/em-http/http_connection.rb#L172

EM (1.0.3) tls implementation : 
* https://github.com/eventmachine/eventmachine/blob/v1.0.3/lib/em/connection.rb#L407

**Comment by damm** [comment]
@BarthV i'm using Authentication you are too I assume with a influxdb.com hosted service? Not using SSL just not seeing any traffic come to the server.

I'll see what I can dig up later.

**Comment by BarthV** [comment]
I'm still working on this.

**Comment by BarthV** [comment]
@masterkorp : 
* after many hours of reasearch, tests & IRC, Sensu's embedded EM seems really not to be ssl/tls compliant (yet) -> https://trello.com/c/8snBWrut/24-as-a-developer-i-would-like-ruby-eventmachine-to-support-tls-and-additional-ssl-ciphers
* as far as I found on ze interweb, configuring EM to communicates through tls requires some tuning at the EM creation. Which is not possible in our case. (but maybe There is another solution)
* In the future, They may make tls easier to use. But 0 guarantee

First I thought using EM was a great idea : async client, no external dependencies, etc ... I'm still thinking it's elegant and powerful but ...

... But at this point I'm really considering rolling back to InfluxDB official gem -> https://github.com/influxdb/influxdb-ruby. 
Do we really need to "hack" internal EM ? for which benefits ? What is preventing us to use influx gem (like @lusis did first on his own outdated extension ?

The more I think about it , the more I found using influx gem is really the thing to do (rather than rewriting the line protocol by ourselves :rage4: )

What do you think about this ?
May I start this work ?

**Comment by damm** [comment]
I admit i'd like to use the official gem...

**Comment by BarthV** [comment]
I'm working on a new branch using influxdb gem.

For information, here is the irc log extract : 
```
portertech:  BarthV: EM specifies a strict and limit list of ciphers for SSL/TLS
portertech:  also,  I recall EM requiring SSLv2 upgrade in order to work w/ TLS
portertech:  I need to revisit, it has been a year since I last investigated
portertech:  I ran into issues writing more sensu transports (stomp etc)
portertech:  as some brokers only supported ciphers that em/ruby doesn't support
portertech:  I plan to submit a fix/option arg to em
```

**Comment by BarthV** [comment]
@damm : you can try / test this version -> https://github.com/BarthV/sensu-influxdb-extension/tree/influx0.9-gem

It's still a "work in progress", but it's working for me :) .. and there's no doc atm.
Any review or feedback appreciated btw.

**Comment by damm** [comment]
@BarthV not bad; I am using the `system_profiler` extension to collect system metrics and noticed a few things.

`txbytes` seems to be stored incorrectly? I'll paste the InfluxQL and then what the http response is.
```
name: txbytes
-------------
time			agent	device	host	plugin	value
2015-10-25T23:52:56Z	sensu	lo	sensu	net	1.06896887776e+12
2015-10-25T23:52:56Z	sensu	eth0	sensu	net	5.0818378865e+11
2015-10-25T23:53:06Z	sensu	lo	sensu	net	1.068969836459e+12
2015-10-25T23:53:06Z	sensu	eth0	sensu	net	5.0818428848e+11
2015-10-25T23:53:16Z	sensu	eth0	sensu	net	5.08184790587e+11
2015-10-25T23:53:16Z	sensu	lo	sensu	net	1.068970748238e+12
2015-10-25T23:53:26Z	sensu	lo	sensu	net	1.068971931197e+12
2015-10-25T23:53:26Z	sensu	eth0	sensu	net	5.08185280954e+11
2015-10-25T23:53:36Z	sensu	lo	sensu	net	1.068972864292e+12
2015-10-25T23:53:36Z	sensu	eth0	sensu	net	5.08185777746e+11
```
```
{"results":[{"series":[{"name":"txbytes","tags":{"host":"sensu"},"columns":["time","derivative"],"values":[[1445817160000,1.06896887776e+12],[1445817180000,1.870478e+06],[1445817200000,2.116054e+06],[1445817220000,2.105039e+06],[1445817240000,1.875311e+06],[1445817260000,2.115741e+06],[1445817280000,2.102901e+06],[1445817300000,1.87814e+06],[1445817320000,2.110756e+06],[1445817340000,2.102755e+06],[1445817360000,1.872754e+06],[1445817380000,2.11202e+06],[1445817400000,2.107616e+06],[1445817420000,1.872223e+06],[1445817440000,2.099219e+06],[1445817460000,2.109927e+06],[1445817480000,1.875241e+06],[1445817500000,2.109188e+06],[1445817520000,2.090891e+06],[1445817540000,1.860617e+06],[1445817560000,2.112398e+06],[1445817580000,2.122385e+06],[1445817600000,1.85988e+06],[1445817620000,1.938861e+06],[1445817640000,-1.069015298155e+12],[1445817660000,0],[1445817680000,0],[1445817700000,0],[1445817720000,0],[1445817740000,0],[1445817760000,0],[1445817780000,0],[1445817800000,0],[1445817820000,0],[1445817840000,0],[1445817860000,0],[1445817880000,0],[1445817900000,0],[1445817920000,0],[1445817940000,0],[1445817960000,0],[1445817980000,0],[1445818000000,0],[1445818020000,0],[1445818040000,0]]}]},{"series":[{"name":"rxbytes","tags":{"host":"sensu"},"columns":["time","derivative"],"values":[[1445817160000,1.06896887776e+12],[1445817180000,1.870478e+06],[1445817200000,2.116054e+06],[1445817220000,2.105039e+06],[1445817240000,1.875311e+06],[1445817260000,2.115741e+06],[1445817280000,2.102901e+06],[1445817300000,1.87814e+06],[1445817320000,2.110756e+06],[1445817340000,2.102755e+06],[1445817360000,1.872754e+06],[1445817380000,2.11202e+06],[1445817400000,2.107616e+06],[1445817420000,1.872223e+06],[1445817440000,2.099219e+06],[1445817460000,2.109927e+06],[1445817480000,1.875241e+06],[1445817500000,2.109188e+06],[1445817520000,2.090891e+06],[1445817540000,1.860617e+06],[1445817560000,2.112398e+06],[1445817580000,2.122385e+06],[1445817600000,1.85988e+06],[1445817620000,1.938861e+06],[1445817640000,-1.069015298155e+12],[1445817660000,0],[1445817680000,0],[1445817700000,0],[1445817720000,0],[1445817740000,0],[1445817760000,0],[1445817780000,0],[1445817800000,0],[1445817820000,0],[1445817840000,0],[1445817860000,0],[1445817880000,0],[1445817900000,0],[1445817920000,0],[1445817940000,0],[1445817960000,0],[1445817980000,0],[1445818000000,0],[1445818020000,0],[1445818040000,0]]}]}]}
```

**Comment by damm** [comment]
I tried swapping https://github.com/BarthV/sensu-influxdb-extension/blob/influx0.9-gem/influxdb.rb#L55 to a integer and it did not seem to create the measurement.

No error however.

It looks like it was being set as an integer https://github.com/sensu/sensu-community-plugins/blob/master/extensions/checks/system_profile.rb#L182 

However it works beautifully other than this.

**Comment by BarthV** [comment]
It work :), you're mixing up float absolute value and float string representation (which is using scientific notation).

Just read that :
_influx-test.rb (extract)_
```ruby
# big float incoming
float = rand * (999999999999999.999) + 10000.0
hash = { "float" => float }

puts float
puts float.to_f
puts hash.to_json

values = { value: float.to_f }
data = [{ series: 'test.float', tags: { justfor: 'damm' }, values: values }]

influxdb = ::InfluxDB::Client.new influx_conf
influxdb.write_points(data)
```

_output:_
```
> ruby influx-test.rb
606803208259525.6
606803208259525.6
{"float":606803208259525.6}

> ruby influx-test.rb
677558455441748.8
677558455441748.8
{"float":677558455441748.8}

> ruby influx-test.rb
471376962683441.0
471376962683441.0
{"float":471376962683441.0}
[...]

```

_on influx_ :
```
> select * from "float.works"
name: float.works
-----------------
time			justfor	value
2015-10-26T10:17:33Z	damm	6.068032082595256e+14
2015-10-26T10:17:56Z	damm	6.775584554417488e+14
2015-10-26T10:18:00Z	damm	4.71376962683441e+14
2015-10-26T10:18:08Z	damm	9.857103251812222e+14
2015-10-26T10:18:19Z	damm	5.774670132278221e+14
[...]
```

_and voilà :_
works

**Comment by damm** [comment]
This actually is using a series that I have to use a derivative to use; it's the actual 'bytes' out of a network interface.

I should have made a screen shot; it was going up and down and the Top Axis was 121 TB and the bottom was -121 TB.

But your right; it's a matter of conversion and maybe not converting unless it's a string is best.  Then we could tackle any plugins that are not acting right ..

Maybe I should just move from system_profiler to metric checks for each ..

**Comment by BarthV** [comment]
@damm
I just pushed a fix on 0.9-gem branch.
`async: true` caused a huge performance drop inside sensu.

Don't really know why, but I had to remove this option and reduce retry number.

**Comment by BarthV** [comment]
I'm hitting strange performances issue ... So I'm wondering how the write method could affect perfs...

__So let's make a quick review : influx gem VS eventmachine__
_All tests were made on the same server, with the same amount of metrics events_
_running with almost 15K write / minute for this test_
_ using http only (https not available when using EM)_

When using eventmachine (`influx-0.9` branch): 
* __constant__ ~270 extension call / s 
* our measurements are written almost in real time (no delay between the extension / write function call and the effective http request)
* load1 = 1 , cpu for sensu-server is 70~90%
i1


When using influxdb gem (`influx-0.9-gem` branch):
* ~170 extension call / s after sensu-server start (t=0)
__170*60 = ~10200 call / min ! This is not enough to handle the incoming 15K metrics / min !__
* the more you are writing at this rate, the more your measurements will be falling behind
* and stil ~170 ext call / s at t=10min

After (re)start (the first blank is the downtime needed to change influx extension :
i2

At T=10min
i3

At T=25min -> We have more than 8 minutes shift
i4


__ Conclusion : __
I think there is something that prevent influxdb gem to proceed more than 10000 writes per minute.
Or maybe there is some kind of ruby call limit inside sensu runtime environement.

Still investigating

**Comment by BarthV** [comment]
So I'm still working on `influxdb` gem (really want to make it works)

I tried back `async` writer and I have modified the following hardcoded constants inside influxdb gem : 
```ruby
        MAX_POST_POINTS = 10_000 # default 1_000
        MAX_QUEUE_SIZE = 50_000 # default 10_000
        NUM_WORKER_THREADS = 200 # default 3
        SLEEP_INTERVAL = 2 # default 5
```

With this values, the writer is now much more powerful and faster (and it is burning cpu way faster too)

There is no more time shift when writing data to sensu. Almost real time data are available.
At the moment, the only way to change this values is to modify the gem files by hand.

Related issue : https://github.com/influxdb/influxdb-ruby/issues/107

**Comment by BarthV** [comment]
But there's still some facts : 
* eventmachine is lighter, faster and with a tight integration with Sensu

**Comment by sodabrew** [comment]
@BarthV Regarding the 100% CPU issue, try using EventMachine 1.0.4 or higher with async and see if that helps. There was a bug in em <= 1.0.3 that manifested as 100% CPU usage in certain scenarios.

**Comment by BarthV** [comment]
@sodabrew 
`eventmachine (1.0.8)`
9stnvwv

But it's not a constant 100% / load 1, the load varies depending on the incoming metrics (the load is "1" but the cpu used by sensu varies between 70 and 90%)

And the system seems unaffected by this charge, It is not really a concern for now.

**Comment by jhrv** [comment]
I had a similar problem at my project and created a extension for what seems like a comparable usecase. https://github.com/jhrv/sensu-influxdb-extension/blob/master/influxdb-extension.rb

Is this something you can reuse ? (code-wise, not necessarily the whole extension). Im just using standard http library and line protocol.

We are currently running ~700 reqs/s with this extension using 2 instances of sensu-server.

**Comment by BarthV** [comment]
@jhrv : thanks for your link ! I didn't found it on my previous research.

This is exactly what we are targeting :) (and influxdb gem is also using `net/http` library and managing its own threads & queue ... but -maybe- not in a optimal way ).

In my opnion `net/http` is a little bit "low level" : we'll have to manage (yet another) thread factory, query queueing , exceptions handlers, etc ... Everything that is already covered by Sensu available eventmachine.

So you gave us a great & beautiful working solution ATM (and I'll read it a bit more for sure) but if I'd to choose beetween `net/http` and `eventmachine` for managing a huge load of async queries, my choice will always be to `eventmachine`. _but please correct if I am wrong_

Maybe we can work on this base at the moment :) but I really think EM TLS/SSL cipher support will unlock the best solution here.

Any other opinions are welcome ofc !

**Comment by BarthV** [comment]
@jhrv : 
I stressed your extension with ~1000 req/s

I measured something like ~250 ext-call/s wich is quite good.

But there's something more problematic for me : There's a problem in threading and http connections

It seems that many requests are reusing the same TCP socket. And when comes the time for one of the thread to do `request.finish` call, ther's still something on the pipe ! It cause data loss :-/ 

Please look here a TCP session : we see multiple POST http and the final one is truncated.
screenshot from 2015-10-30 11 22 12
In a RESTful world, I want to see a single TCP connection and a single http POST into it.

Since EM will be compatible with custom TLS ciphers in the next release I'll continue to work with it :-)

**Comment by BarthV** [comment]
Following great advices on #sensu IRC channel, I'll work on requests buffering/batching inside this extension.
This will dramatically reduce the number of HTTP calls.

**Comment by jhrv** [comment]
Nice! I haven't really tested it like this (I would be really interested in knowing how your test-rig looks like). However I'm not experiencing the same behaviour as you with dataloss but this might be due to lower load. Our requirements is more that of speed than not losing data, but I'll definately look into improving this.

**Comment by BarthV** [comment]
I found out why I couldn't go faster than 15K points/min !

Sensu core seems to be running only on 1 core.
In my setup this Sensu instance can queue out ~15000 results/min (and no more)
So my results queue was growing faster than light (I'm running 80K points/min ATM)

So the requests caching was not necessary, but I still did it.

What I did : 
* Rework the EM script to use a trivial cache ( https://github.com/BarthV/sensu-influxdb-extension/tree/influx0.9-embuffer )
* This cache flush every X seconds or when cache limit is reached (Y items) (defaults : 6s - 300 items)
* It reduce dramatically http requests flow.
* I started few more instance on the same machine.
* warning : SSL is stil broken (Sensu Ruby is __still__ not compatible with much TLS/SSL ciphers...)

And that's all .. my server can now process +80K results in real time with almost not load on the server.
In theory, I would be able to reach +150K results/min (2500 results/sec).

**Comment by damm** [comment]
Nice!

**Comment by masterkorp** [comment]
@BarthV Sorry for the time taken, I could only upgrade my InfluxDB to 0.9 yesterday.

This works!

I also accept PRs with the perfomance improvements!

**Pull request merged**
