### PR TITLE
Stop calling parse settings in every loop

### PR DESCRIPTION
**Pull request by BarthV**
* Changed var name ```settings``` -> ```conf``` to avoid confusion with ```@settings```
* ```parse_settings()``` is no more called for every line

### CODE REVIEW

**Comment by BarthV** [comment]
:up: 
@masterkorp ?

**Comment by BarthV** [comment]
:up: :angel:

**Comment by BarthV** [comment]
:arrow_up:

**Comment by masterkorp** [comment]
Thanks, sorry for the delay!

**Pull request merged**
